#!/usr/bin/env bash
# 启用 HTTPS（ADR-0047 / ADR-0004）：域名就绪后一次性执行。
#
# 用法：
#   bash scripts/prod/enable-tls.sh <域名> [certbot 邮箱]
#   bash scripts/prod/enable-tls.sh --renew            # 续期（cron 调用）
#
# 机制：短暂停 server 容器释放 80 端口 → certbot standalone 签发 → 生成
# docker-compose.prod.tls.yml（挂载 nginx.tls.conf 与证书）→ 重建 server。
# 此后 deploy.sh/restart.sh 自动叠加该片段。续期由每周 cron 调 --renew，
# 签发与续期期间 server 各停约数十秒（分钟级停机窗口可接受，ADR-0047）。
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

TLS_MARK=".tls-domain"
compose_files=(-f docker-compose.yml -f docker-compose.prod.yml)

renew() {
  [ -f "$TLS_MARK" ] || { echo "enable-tls: no $TLS_MARK — TLS not enabled yet" >&2; exit 1; }
  DOMAIN="$(cat "$TLS_MARK")"
  compose_files+=(-f docker-compose.prod.tls.yml)
  echo "enable-tls: renewing certificate for $DOMAIN ..."
  docker compose "${compose_files[@]}" stop server
  docker run --rm -p 80:80 -v "$REPO_ROOT/letsencrypt:/etc/letsencrypt" \
    certbot/certbot renew --standalone --cert-name "$DOMAIN"
  docker compose "${compose_files[@]}" up -d --wait --wait-timeout 300 server
  echo "enable-tls: renewal done."
  exit 0
}

if [ "${1:-}" = "--renew" ]; then renew; fi

DOMAIN="${1:-}"
EMAIL="${2:-}"
if [ -z "$DOMAIN" ]; then
  echo "enable-tls: usage: $0 <domain> [email]  (or --renew)" >&2
  exit 1
fi

echo "enable-tls: issuing certificate for $DOMAIN (standalone, port 80)..."
docker compose "${compose_files[@]}" stop server
docker run --rm -p 80:80 -v "$REPO_ROOT/letsencrypt:/etc/letsencrypt" \
  certbot/certbot certonly --standalone -d "$DOMAIN" --agree-tos \
  ${EMAIL:+-m "$EMAIL"} ${EMAIL:-"--register-unsafely-without-email"} \
  --cert-name "$DOMAIN"

echo "enable-tls: generating docker-compose.prod.tls.yml ..."
cat > docker-compose.prod.tls.yml <<EOF
# Generated by scripts/prod/enable-tls.sh — HTTPS enabled for $DOMAIN.
# 路由配置来自镜像内 nginx.tls.conf（路由集与 nginx.conf 对齐，
# tests/nginx-tls-parity.test.mjs 守护）。删除本文件并重建 server 即回退 HTTP。
services:
  server:
    volumes: !override
      - ./docker/nginx.tls.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt/live/$DOMAIN/fullchain.pem:/etc/nginx/tls/fullchain.pem:ro
      - ./letsencrypt/live/$DOMAIN/privkey.pem:/etc/nginx/tls/privkey.pem:ro
EOF

echo "$DOMAIN" > "$TLS_MARK"

echo "enable-tls: switching server to TLS..."
compose_files+=(-f docker-compose.prod.tls.yml)
docker compose "${compose_files[@]}" up -d --wait --wait-timeout 300 server

echo "enable-tls: installing weekly renewal cron (Monday 03:30)..."
(crontab -l 2>/dev/null | grep -v 'enable-tls\.sh' || true;
 echo "30 3 * * 1 cd '$REPO_ROOT' && bash scripts/prod/enable-tls.sh --renew >> '$REPO_ROOT/backups/tls-renew.log' 2>&1") | crontab -

echo "enable-tls: verifying HTTPS..."
curl -fsS -o /dev/null "https://$DOMAIN/health" || {
  echo "enable-tls: HTTPS health check failed — check DNS ($DOMAIN → this host?)" >&2
  exit 1
}
echo "enable-tls: done — https://$DOMAIN is live."
